---
- name: Common baseline (hostname + firewall + base packages)
  hosts: "all:!master:!controller"
  become: true
  gather_facts: true
  any_errors_fatal: true

  roles:
    - hosts_file
    - hostname_normalize
    - common
    - cluster_nftables
