---
# Global SSH / privilege escalation
ansible_user: ansible
ansible_become: true
ansible_become_method: sudo
ansible_become_flags: "-n"
ansible_python_interpreter: /usr/bin/python3

# Your DNS resolvers (used by dns.sh and optional tasks)
dns_resolvers:
  - 10.100.10.2
  - 10.100.10.3

# Optional: if you want strict IPv4 usage everywhere
force_ipv4: true

# Optional: Salt version expectations
salt_expected_version: "3006"
