- name: Install apt prereqs
  apt:
    name: [ca-certificates, curl, gnupg]
    state: present
    update_cache: yes

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Kubernetes signing key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_minor_repo }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-{{ k8s_minor_repo }}.gpg
    mode: "0644"

- name: Add Kubernetes repo
  apt_repository:
    repo: >
      deb [signed-by=/etc/apt/keyrings/kubernetes-{{ k8s_minor_repo }}.gpg]
      https://pkgs.k8s.io/core:/stable:/{{ k8s_minor_repo }}/deb/ /
    state: present
    filename: kubernetes

- name: Install kubelet/kubeadm/kubectl
  apt:
    name: [kubelet, kubeadm, kubectl]
    state: present
    update_cache: yes

- name: Hold kube packages
  command: apt-mark hold kubelet kubeadm kubectl
  changed_when: false

- name: Pin kubelet to 10.100 node IP
  copy:
    dest: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS=--node-ip={{ k8s_node_ip }}

- name: Enable kubelet
  service:
    name: kubelet
    enabled: true
    state: restarted

