- import_playbook: 00_preflight.yml
- import_playbook: 01_common.yml
- import_playbook: 02_containerd.yml
- import_playbook: 03_k8s_packages.yml
- import_playbook: 04_lb.yml
- import_playbook: 05_cp_init.yml
- import_playbook: 06_cp_join.yml
- import_playbook: 07_worker_join.yml
- import_playbook: 08_cilium.yml
- import_playbook: 09_ingress.yml
- import_playbook: 10_monitoring.yml
- import_playbook: 99_verify.yml
