# Allow etcd ports on nodes in the etcd group
cluster_nftables_extra_tcp_ports:
  - 2379
  - 2380

# Trust the etcd underlay peers (adjust if you want to restrict even more)
cluster_nftables_trusted_cidrs:
  - 10.100.10.218/32
  - 10.100.10.219/32
  - 10.100.10.220/32

