- name: Render prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: "0644"
  notify: restart_prometheus

- name: Ensure prometheus service enabled
  service:
    name: prometheus
    enabled: true
    state: started
